version: '3.7'

services:
  api-assinatura:
    container_name: api-assinatura
    build:
      dockerfile: Dockerfile
    image: api-assinatura:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1090:80