version: '3.7'

services:
  api-polycron:
    container_name: api-polycron
    build:
      dockerfile: Dockerfile
    environment:
      Database_Name: "Polycron"
      Database_Host: "server.polycron.com.br, 2354"
      Database_Username: "sa"
      Database_Password: "P@ssword00"
    image: api-polycron:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1090:80